# Generated by Django 5.1.15 on 2026-05-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('card', 'Card'), ('crypto', 'Crypto')], max_length=16)),
                ('provider', models.CharField(help_text='Merchant-facing provider code, such as acquirer-us or btc-wallet-primary.', max_length=40)),
                ('adapter', models.CharField(blank=True, help_text='Fox Pay adapter type, such as hosted, mock, or manual. Defaults to provider.', max_length=40)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='payments.merchant')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'kind', 'provider'), name='unique_merchant_provider_kind')],
            },
        ),
    ]
