# Generated by Django 5.1.15 on 2026-09-13 00:11

import apps.payments.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_providerconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_dispute_id', models.CharField(blank=True, max_length=160)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='needs_response', max_length=40)),
                ('evidence_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(max_length=24)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(max_length=40)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tg11_user_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('administrator', 'Administrator'), ('developer', 'Developer'), ('finance', 'Finance'), ('support', 'Support'), ('viewer', 'Viewer')], default='viewer', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantWebhookAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=160)),
                ('enabled_events', models.JSONField(blank=True, default=list)),
                ('secret_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(default=apps.payments.models.payment_link_token, max_length=80, unique=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('enabled_payment_methods', models.JSONField(blank=True, default=list)),
                ('allow_customer_amount', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(max_length=180)),
                ('type', models.CharField(max_length=32)),
                ('display_metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('encrypted_value', models.TextField()),
                ('last_rotated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=120)),
                ('normalized_event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_id', models.CharField(default=apps.payments.models.refund_id, max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='created', max_length=24)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_refund_id', models.CharField(blank=True, max_length=160)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='providerconfig',
            name='unique_merchant_provider_kind',
        ),
        migrations.AddField(
            model_name='apikey',
            name='environment',
            field=models.CharField(default='test', max_length=12),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_type',
            field=models.CharField(choices=[('secret', 'Secret'), ('publishable', 'Publishable')], default='secret', max_length=16),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apikey',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='exchange_rate_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='expected_amount_decimal',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_invoices', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='received_amount_decimal',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='settlement_state',
            field=models.CharField(default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='cryptoinvoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='response_object_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='response_object_type',
            field=models.CharField(default='payment_intent', max_length=80),
        ),
        migrations.AddField(
            model_name='merchant',
            name='environment_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='merchant',
            name='legal_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='merchant',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='merchant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='failure_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='failure_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_response_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='rail',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='capture_strategy',
            field=models.CharField(default='automatic', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='environment',
            field=models.CharField(default='test', max_length=12),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='requested_payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='selected_provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_payment_intents', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='statement_descriptor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='environment',
            field=models.CharField(default='test', max_length=12),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='payments.paymentintent'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('awaiting_payment_method', 'Awaiting payment method'), ('requires_payment_method', 'Requires payment method'), ('pending', 'Pending'), ('processing', 'Processing'), ('requires_action', 'Requires action'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='requires_payment_method', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='providerconfig',
            constraint=models.UniqueConstraint(fields=('merchant', 'environment', 'kind', 'provider'), name='unique_merchant_env_provider_kind'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.customer'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='merchantmembership',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='merchantmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantwebhookendpoint',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='merchantwebhookattempt',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='payments.merchantwebhookendpoint'),
        ),
        migrations.AddField(
            model_name='merchantwebhookevent',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='merchantwebhookattempt',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='payments.merchantwebhookevent'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='paymentmethodreference',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='payments.customer'),
        ),
        migrations.AddField(
            model_name='paymentmethodreference',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_references', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='paymentmethodreference',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_references', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='provider_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_events', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='providerevent',
            name='payment_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='refund',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.merchant'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentattempt'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentintent'),
        ),
        migrations.AddField(
            model_name='refund',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='payments.refund'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('merchant', 'external_id'), name='unique_merchant_customer_external_id'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('merchant', 'code', 'currency'), name='unique_merchant_ledger_account'),
        ),
        migrations.AddConstraint(
            model_name='merchantmembership',
            constraint=models.UniqueConstraint(fields=('merchant', 'user'), name='unique_merchant_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='merchantmembership',
            constraint=models.UniqueConstraint(fields=('merchant', 'tg11_user_uuid'), name='unique_merchant_tg11_membership'),
        ),
        migrations.AddConstraint(
            model_name='providerevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_event'),
        ),
    ]
