# Generated by Django 5.1.15 on 2026-09-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auditlog_customer_dispute_ledgeraccount_ledgerentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwebhookendpoint',
            name='encrypted_secret',
            field=models.TextField(blank=True),
        ),
    ]
