# Generated by Django 5.1.15 on 2026-09-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merchantwebhookendpoint_encrypted_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='cancel_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='success_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
