# Generated by Django 5.1.15 on 2026-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_paymentattempt_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tg11_user_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('merchant', 'tg11_user_uuid'), name='unique_merchant_customer_tg11_user'),
        ),
    ]
