# Generated by Django 5.1.15 on 2026-09-13 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_customer_tg11_user_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(max_length=180)),
                ('plan_name', models.CharField(max_length=160)),
                ('status', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_references', to='payments.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_references', to='payments.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'provider', 'provider_reference'), name='unique_merchant_subscription_reference')],
            },
        ),
    ]
