# Generated by Django 5.1.15 on 2026-09-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscriptionreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCustomerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_reference', models.CharField(max_length=180)),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentmethodreference',
            constraint=models.UniqueConstraint(fields=('provider_config', 'provider_reference'), name='unique_provider_payment_method_reference'),
        ),
        migrations.AddField(
            model_name='providercustomerreference',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_references', to='payments.customer'),
        ),
        migrations.AddField(
            model_name='providercustomerreference',
            name='provider_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_references', to='payments.providerconfig'),
        ),
        migrations.AddConstraint(
            model_name='providercustomerreference',
            constraint=models.UniqueConstraint(fields=('provider_config', 'customer'), name='unique_provider_customer'),
        ),
        migrations.AddConstraint(
            model_name='providercustomerreference',
            constraint=models.UniqueConstraint(fields=('provider_config', 'provider_reference'), name='unique_provider_customer_reference'),
        ),
    ]
