# Generated by Django 5.1.15 on 2026-09-14 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_existing_live_merchants(apps, schema_editor):
    Merchant = apps.get_model('payments', 'Merchant')
    for merchant in Merchant.objects.filter(status='active', is_active=True).only('pk', 'created_at'):
        Merchant.objects.filter(pk=merchant.pk).update(
            live_payments_enabled=True,
            approved_at=merchant.created_at,
            risk_level='legacy',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_providercustomerreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_merchants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='merchant',
            name='live_payments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merchants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='risk_level',
            field=models.CharField(default='unreviewed', max_length=24),
        ),
        migrations.AddField(
            model_name='merchant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='pending', max_length=24),
        ),
        migrations.RunPython(preserve_existing_live_merchants, migrations.RunPython.noop),
        migrations.CreateModel(
            name='MerchantAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_version', models.CharField(max_length=40)),
                ('agreement_hash', models.CharField(max_length=64)),
                ('acceptable_use_version', models.CharField(max_length=40)),
                ('acceptable_use_hash', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_acceptances', to='payments.merchant')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='payments.merchantagreementacceptance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_agreement_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
