# Generated by Django 5.1.15 on 2026-09-14 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def tag_legacy_provider_configs(apps, schema_editor):
    Merchant = apps.get_model('payments', 'Merchant')
    ProviderConfig = apps.get_model('payments', 'ProviderConfig')
    Connection = apps.get_model('payments', 'MerchantProviderConnection')
    Merchant.objects.all().update(allow_legacy_provider_configs=True)
    for config in ProviderConfig.objects.all().iterator():
        provider = config.adapter or config.provider
        if provider == 'stripe_checkout':
            provider = 'stripe'
        if provider not in {'stripe', 'square', 'paypal', 'nowpayments'}:
            continue
        connection = Connection.objects.create(
            merchant_id=config.merchant_id,
            provider=provider,
            environment=config.environment,
            status='active' if config.is_active else 'pending',
            authorization_method='legacy_config',
            connected_at=config.created_at if config.is_active else None,
            metadata={'legacy_provider_config_id': config.pk},
        )
        ProviderConfig.objects.filter(pk=config.pk).update(connection_id=connection.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_seller_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='allow_legacy_provider_configs',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MerchantProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('square', 'Square'), ('paypal', 'Paypal'), ('nowpayments', 'Nowpayments')], max_length=24)),
                ('environment', models.CharField(default='test', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=24)),
                ('authorization_method', models.CharField(max_length=32)),
                ('external_account_id', models.CharField(blank=True, max_length=180)),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('encrypted_access_token', models.TextField(blank=True)),
                ('encrypted_refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='payments.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_configs', to='payments.merchantproviderconnection'),
        ),
        migrations.CreateModel(
            name='ProviderOnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=24)),
                ('environment', models.CharField(max_length=12)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('requested_scopes', models.JSONField(blank=True, default=list)),
                ('encrypted_pkce_verifier', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('return_path', models.CharField(default='/seller/', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to='payments.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='merchantproviderconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('merchant', 'provider', 'environment', 'external_account_id'), name='unique_merchant_provider_account'),
        ),
        migrations.RunPython(tag_legacy_provider_configs, migrations.RunPython.noop),
    ]
