# Generated by Django 5.1.15 on 2026-09-14 21:13

import django.db.models.deletion
import ipaddress
import re
from urllib.parse import urlsplit
from django.db import migrations, models


def preserve_known_live_return_origins(apps, schema_editor):
    PaymentIntent = apps.get_model('payments', 'PaymentIntent')
    AllowedOrigin = apps.get_model('payments', 'MerchantAllowedReturnOrigin')
    for intent in PaymentIntent.objects.filter(environment='live').iterator():
        for value in (intent.success_url, intent.cancel_url):
            if not value:
                continue
            try:
                parsed = urlsplit(value)
                host = parsed.hostname
                port = parsed.port
                if parsed.scheme != 'https' or not host or '@' in parsed.netloc or parsed.fragment or '\\' in value:
                    continue
                try:
                    address = ipaddress.ip_address(host)
                    if not address.is_global:
                        continue
                except ValueError:
                    labels = host.lower().split('.')
                    if len(labels) < 2 or any(not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label) for label in labels):
                        continue
                origin = f'https://{host.lower()}{f":{port}" if port and port != 443 else ""}'
                if len(origin) <= 255:
                    AllowedOrigin.objects.get_or_create(merchant_id=intent.merchant_id, origin=origin)
            except ValueError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_provider_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAllowedReturnOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_return_origins', to='payments.merchant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'origin'), name='unique_merchant_return_origin')],
            },
        ),
        migrations.RunPython(preserve_known_live_return_origins, migrations.RunPython.noop),
    ]
