# Generated by Django 5.1.15 on 2026-09-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_allowed_return_origins'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwebhookendpoint',
            name='pending_encrypted_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchantwebhookendpoint',
            name='pending_secret_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantwebhookendpoint',
            name='pending_secret_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
