# Generated by Django 5.1.15 on 2026-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_webhook_secret_rotation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='merchantproviderconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('provider', 'environment', 'external_account_id'), name='unique_provider_account_owner'),
        ),
    ]
