# Generated by Django 5.1.15 on 2026-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_unique_connected_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantproviderconnection',
            name='token_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
