# Generated by Django 5.1.15 on 2026-09-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_square_token_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideronboardingsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
