# Generated by Django 5.1.15 on 2026-09-15 02:50

import apps.payments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_refund_provider_idempotency(apps, schema_editor):
    Refund = apps.get_model("payments", "Refund")
    for refund_id in Refund.objects.values_list("pk", flat=True).iterator():
        Refund.objects.filter(pk=refund_id).update(provider_idempotency_key=uuid.uuid4().hex)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_provider_onboarding_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('environment', models.CharField(max_length=12)),
                ('rule_code', models.CharField(max_length=80)),
                ('severity', models.CharField(default='high', max_length=16)),
                ('status', models.CharField(default='open', max_length=24)),
                ('request_ip_hash', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=240)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('restricted_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dispute',
            name='payment_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='payments.paymentattempt'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='provider_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='payments.providerconfig'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='routing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='temporarily_restricted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='temporary_restriction_reason',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='request_ip_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='refund',
            name='failure_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='refund',
            name='failure_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='refund',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='provider_idempotency_key',
            field=models.CharField(default='', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='provider_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_dispute_id', ''), _negated=True), fields=('merchant', 'provider', 'provider_dispute_id'), name='unique_merchant_provider_dispute'),
        ),
        migrations.RunPython(populate_refund_provider_idempotency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='refund',
            name='provider_idempotency_key',
            field=models.CharField(default=apps.payments.models.provider_operation_id, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('provider_idempotency_key',), name='unique_refund_provider_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('merchant', 'idempotency_key'), name='unique_merchant_refund_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id', ''), _negated=True), fields=('merchant', 'provider', 'provider_refund_id'), name='unique_merchant_provider_refund'),
        ),
        migrations.AddField(
            model_name='abusealert',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_alerts', to='payments.merchant'),
        ),
        migrations.AddIndex(
            model_name='abusealert',
            index=models.Index(fields=['merchant', 'status', 'created_at'], name='payments_ab_merchan_e3bdc9_idx'),
        ),
    ]
